export const SHOWS_LOAD = 'SHOWS_LOAD';
export const SHOWS_LOAD_SUCCESS = 'SHOWS_LOAD_SUCCESS';
export const SHOWS_LOAD_FAILURE = 'SHOWS_LOAD_FAILURE';

export const SHOWS_RESET = 'SHOWS_RESET';

export const SHOWLIST_LOAD = 'SHOWLIST_LOAD';
export const SHOWLIST_LOAD_SUCCESS = 'SHOWLIST_LOAD_SUCCESS';
export const SHOWLIST_LOAD_FAILURE = 'SHOWLIST_LOAD_FAILURE';

export const SHOWLIST_RESET = 'SHOWLIST_RESET';

export const SHOW_PLAYLIST_LOAD = 'SHOW_PLAYLIST_LOAD';
export const SHOW_PLAYLIST_LOAD_SUCCESS = 'SHOW_PLAYLIST_LOAD_SUCCESS';
export const SHOW_PLAYLIST_LOAD_FAILURE = 'SHOW_PLAYLIST_LOAD_FAILURE';

export const SHOW_PLAYLIST_RESET = 'SHOW_PLAYLIST_RESET';
