export const NEWS_LOAD = 'NEWS_LOAD';
export const NEWS_LOAD_SUCCESS = 'NEWS_LOAD_SUCCESS';
export const NEWS_LOAD_FAILURE = 'NEWS_LOAD_FAILURE';

export const NEWS_RESET = 'NEWS_RESET';

export const NEWSLIST_LOAD = 'NEWSLIST_LOAD';
export const NEWSLIST_LOAD_SUCCESS = 'NEWSLIST_LOAD_SUCCESS';
export const NEWSLIST_LOAD_FAILURE = 'NEWSLIST_LOAD_FAILURE';

export const NEWSLIST_RESET = 'NEWSLIST_RESET';

export const NEWS_PLAYLIST_LOAD = 'NEWS_PLAYLIST_LOAD';
export const NEWS_PLAYLIST_LOAD_SUCCESS = 'NEWS_PLAYLIST_LOAD_SUCCESS';
export const NEWS_PLAYLIST_LOAD_FAILURE = 'NEWS_PLAYLIST_LOAD_FAILURE';

export const NEWS_PLAYLIST_RESET = 'NEWS_PLAYLIST_RESET';
