export const SONGS_LOAD = 'SONGS_LOAD';
export const SONGS_LOAD_SUCCESS = 'SONGS_LOAD_SUCCESS';
export const SONGS_LOAD_FAILURE = 'SONGS_LOAD_FAILURE';

export const SONGS_RESET = 'SONGS_RESET';

export const SONGLIST_LOAD = 'SONGLIST_LOAD';
export const SONGLIST_LOAD_SUCCESS = 'SONGLIST_LOAD_SUCCESS';
export const SONGLIST_LOAD_FAILURE = 'SONGLIST_LOAD_FAILURE';

export const SONGLIST_RESET = 'SONGLIST_RESET';

export const SONG_PLAYLIST_LOAD = 'SONG_PLAYLIST_LOAD';
export const SONG_PLAYLIST_LOAD_SUCCESS = 'SONG_PLAYLIST_LOAD_SUCCESS';
export const SONG_PLAYLIST_LOAD_FAILURE = 'SONG_PLAYLIST_LOAD_FAILURE';

export const SONG_PLAYLIST_RESET = 'SONG_PLAYLIST_RESET';
